# Generated by Django 2.1.1 on 2018-09-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='report',
            field=models.IntegerField(),
        ),
    ]
